/** Navigable pages for the home command palette (temporary design helpers). */
export const SEARCH_PAGES = [
  {
    route: 'home',
    labelKey: 'home2-nav-dashboard',
    descKey: 'home2-search-desc-home',
    icon: 'home',
    keywords: 'dashboard inicio home',
  },
  {
    route: 'bots',
    labelKey: 'bots',
    descKey: 'home2-search-desc-bots',
    icon: 'users',
    keywords: 'bots accounts',
  },
  {
    route: 'commands',
    labelKey: 'commands',
    descKey: 'home2-search-desc-commands',
    icon: 'laptop',
    keywords: 'commands terminal',
  },
  {
    route: 'log',
    labelKey: 'log',
    descKey: 'home2-search-desc-log',
    icon: 'file-alt',
    keywords: 'log registro',
  },
  {
    route: 'plugins',
    labelKey: 'plugins',
    descKey: 'home2-search-desc-plugins',
    icon: 'puzzle-piece',
    keywords: 'plugins',
  },
  {
    route: 'releases',
    labelKey: 'releases',
    descKey: 'home2-search-desc-releases',
    icon: 'code-branch',
    keywords: 'releases versiones',
  },
  {
    route: 'configuration',
    labelKey: 'configuration',
    descKey: 'home2-search-desc-configuration',
    icon: 'cogs',
    keywords: 'configuration config settings',
  },
  {
    route: 'asf-config',
    labelKey: 'asf-config',
    descKey: 'home2-search-desc-asf-config',
    icon: 'edit',
    keywords: 'config asf',
  },
  {
    route: 'mass-editor',
    labelKey: 'mass-editor',
    descKey: 'home2-search-desc-mass-editor',
    icon: 'paste',
    keywords: 'mass editor',
  },
  {
    route: 'ui-config',
    labelKey: 'ui-config',
    descKey: 'home2-search-desc-ui-config',
    icon: 'wrench',
    keywords: 'ui interface',
  },
  {
    route: 'asf-bans',
    labelKey: 'asf-bans',
    descKey: 'home2-search-desc-asf-bans',
    icon: 'ban',
    keywords: 'bans ip',
  },
];
